In [2]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [4]:
vector = np.arange(1, 11)

In [5]:
vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.


In [6]:
matrix_zero = np.zeros((3, 3))

In [7]:
matrix_zero


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [14]:
random_array = np.random.randint(1, 11, size=(5, 5))
print(random_array)

[[ 8  7  1  2 10]
 [ 9  1  6  2  8]
 [ 7  4  5  7  5]
 [10  4  1  8  6]
 [ 3  7  2 10 10]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [15]:
random_array = np.random.randint(0, 2, size=(4, 4))
print(random_array)

[[0 1 0 1]
 [0 0 0 0]
 [1 0 1 1]
 [1 0 1 1]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [16]:
a = np.random.randint(1, 11, size=5)
b = np.random.randint(1, 11, size=5)
print(a)
print(b)
print(a + b)
print(a - b)
print(a * b)

[5 8 5 9 7]
[10  3  7  1  8]
[15 11 12 10 15]
[-5  5 -2  8 -1]
[50 24 35  9 56]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [20]:
vector1 = np.array([2, 5, 8, 3, 1, 6, 7])
vector2 = np.array([9, 1, 4, 7, 6, 5, 2])
scalar = np.dot(vector1, vector2)
scalar

126

7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [25]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)

result = np.dot(matrix1, matrix2)

print("Result:\n", result)

Matrix 1:
 [[ 6 10]
 [ 1  1]]
Matrix 2:
 [[ 5  5  2]
 [ 3  5 10]]
Result:
 [[ 60  80 112]
 [  8  10  12]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [31]:
matrix = np.random.randint(1, 11, size=(3, 3))
print(matrix, "\n")
print(np.linalg.inv(matrix))

[[ 4  7  1]
 [ 8  2  4]
 [ 9  1 10]] 

[[-0.06299213  0.27165354 -0.1023622 ]
 [ 0.17322835 -0.12204724  0.03149606]
 [ 0.03937008 -0.23228346  0.18897638]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.


In [33]:
matrix = np.random.randint(1, 11, size=(4, 4))
print(matrix, "\n")
print(matrix.T)

[[ 3  9  8  3]
 [ 4  6  8  8]
 [ 3  4  8  6]
 [ 9  7 10  5]] 

[[ 3  4  3  9]
 [ 9  6  4  7]
 [ 8  8  8 10]
 [ 3  8  6  5]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [35]:
matrix = np.random.randint(1, 11, size=(3, 4))
print("Matrix:\n", matrix)
vector = np.random.randint(1, 11, size=4)
print("Vector:\n", vector)
print("Result:\n", np.dot(matrix, vector))

Matrix:
 [[ 9  5  2  6]
 [ 4  5  2  7]
 [ 5 10  3  8]]
Vector:
 [5 6 7 2]
Result:
 [101  78 122]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [38]:
matrix = np.random.randint(0, 2, size=(2, 3))
print("Matrix:\n", matrix)
vector = np.random.randint(0, 2, size=3)
print("Vector:\n", vector)
print("Result:\n", np.dot(matrix, vector))

Matrix:
 [[0 1 1]
 [1 1 0]]
Vector:
 [1 1 0]
Result:
 [1 2]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [39]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)

result = matrix1 * matrix2

print("Result:\n", result)

Matrix 1:
 [[6 6]
 [7 1]]
Matrix 2:
 [[6 7]
 [8 1]]
Result:
 [[36 42]
 [56  1]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [40]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)

result = np.dot(matrix1, matrix2)

print("Result:\n", result)

Matrix 1:
 [[2 9]
 [2 8]]
Matrix 2:
 [[5 7]
 [5 4]]
Result:
 [[55 50]
 [50 46]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [42]:
matrix = np.random.randint(1, 101, size=(5, 5))
print("Matrix:\n", matrix)
result = np.sum(matrix)

print("Result:\n", result)

Matrix:
 [[ 93  63  65  77  67]
 [ 38  17  44 100  32]
 [ 36  71  13  99  87]
 [  4  19  54  97  27]
 [ 70   2  12  25  14]]
Result:
 1226


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [44]:
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)

result = matrix1 - matrix2

print("Result:\n", result)

Matrix 1:
 [[4 5 8 6]
 [7 9 3 6]
 [9 8 8 9]
 [2 7 6 9]]
Matrix 2:
 [[ 4  4  3  6]
 [ 5  3  7  9]
 [ 7  4  7  5]
 [10  3  2  4]]
Result:
 [[ 0  1  5  0]
 [ 2  6 -4 -3]
 [ 2  4  1  4]
 [-8  4  4  5]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [48]:
matrix = np.random.randint(0, 2, size=(3, 3))
print("Matrix:\n", matrix)
row_sum = np.sum(matrix, axis=1)

result = row_sum.reshape(3, 1)

print("Result:\n", result)

Matrix:
 [[0 0 1]
 [1 1 1]
 [1 0 1]]
Result:
 [[1]
 [3]
 [2]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [50]:
matrix = np.random.randint(2, 11, size=(3, 4))
print("Matrix:\n", matrix)

result = np.power(matrix, 2)

print("Result:\n", result)

Matrix:
 [[ 9 10  6  4]
 [ 4  3  4  4]
 [ 6  2 10  7]]
Result:
 [[ 81 100  36  16]
 [ 16   9  16  16]
 [ 36   4 100  49]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [51]:
vector = np.random.randint(1, 51, size=4)
print("Vector:\n", vector)

result = np.sqrt(vector)

print("Result:\n", result)

Vector:
 [42 46 12 36]
Result:
 [6.4807407  6.78232998 3.46410162 6.        ]
